name: nedo_halo
description: NEDO HALO safety system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/halo_icon.png
    - assets/images/nedo_halo_logo.png
    - assets/images/halo_shieldLogoWht.png

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/halo_icon.png
  remove_alpha_ios: true
