name: nedo_halo
description: NEDO HALO safety system
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^5.6.12
  firebase_auth: ^5.6.3
  firebase_core: ^3.15.2
  firebase_storage: ^12.4.10
  http: ^1.2.2
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true

  assets:
    - assets/images/halo_icon.png
    - assets/images/nedo_halo_logo.png
    - assets/images/halo_shieldLogoWht.png

  fonts:
    - family: Orbitron
      fonts:
        - asset: assets/fonts/Orbitron-VariableFont_wght.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/images/halo_icon.png
  remove_alpha_ios: true
